on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  reusable_workflow_jobs:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/labeler@v4
